### ISSUE TITLE
Using pytest-memray in CI

### ISSUE THREAD

**Issue by aminalaee** [microsoft/picologging#175]
pytest-memray decorators are added but they are not used in the CI:
https://github.com/microsoft/picologging/actions/runs/6349273564/job/17247238249

Is that intentional? Running the tests locally the allowed leak values need to be configured I think.

**Comment by tonybaloney** [comment]
It was intentional. There was a blog (ironically a memory leak) in memray that I raised. It's since been fixed. I need to update the memray versions for CI
