### ISSUE TITLE
Using `asctime` in formatter messes up timestamp encoding

### ISSUE THREAD

**Issue by aranvir** [microsoft/picologging#203]
Using the example below, picologging produces messy encoding for timestamps, e.g.:
```
INFO - �i�j,-1224597123 - root - <unknown> - A log message!
WARNING - HE��,-1224597123 - root - <unknown> - A log message with arguments
```

Using the standard library the same code produces the expected result:
```
INFO - 2024-02-17 13:14:50,850 - root - logging_demo - A log message!
WARNING - 2024-02-17 13:14:50,850 - root - logging_demo - A log message with arguments
```

This has been tested with picologging 0.9.3 on Ubuntu 22.04 with Python 3.10.12 and with picologging 0.9.6 on Win10 with Python 3.11.7. This also happens for lower versions (0.8.x, 0.7.x, 0.6.x) but with less intensity, e.g.:

```
LINUX:
INFO - 2024-02-17 13:23:59,-1224344203 - root - <unknown> - A log message!
WARNING - 2024-02-17 13:23:59,-1224344203 - root - <unknown> - A log message with arguments

WINDOWS:
INFO - ,-1224369277 - root - <unknown> - A log message!
WARNING - ,-1224369276 - root - <unknown> - A log message with arguments
```

## Example:
```python
import picologging as logging
# import logging
logging.basicConfig(format="%(levelname)s - %(asctime)s - %(name)s - %(module)s - %(message)s")

logger = logging.getLogger()
logger.setLevel(logging.INFO)
logger.info("A log message!")
logger.warning("A log message with %s", "arguments")

if __name__ == '__main__':
    pass
```

**Comment by tarasko** [comment]
Well, it is not an encoding issue, it is an attempt to print an uninitialized buffer here:
https://github.com/microsoft/picologging/blob/e648cb336d1f86053af342129c7d170672a76886/src/picologging/formatter.cxx#L101

If you're lucky it doesn't crash python, but on a bad day it can. One way to work this around is to pass datefmt argument to basicConfig. 
datefmt = "%D %T"
This will activate a different path in the code that doesn't have a bug. But still it is not possible to print (milli/micro)seconds.

**Comment by tarasko** [comment]
I made a PR that fixes the issue
https://github.com/microsoft/picologging/pull/208
