### ISSUE TITLE
Non-blocking logger

### ISSUE THREAD

**Issue by Goldziher** [microsoft/picologging#39]
Hi there,

First thanks for this library - python really needs something like this. Secondly - I currently implement non-blocking logging using the `QueueListener` from the stlib logging library. You can see this for example [here](https://github.com/starlite-api/starlite/blob/main/starlite/logging.py#L18).  Using the `QueueListener` and `QueueHandler` logging becomes non-blocking, which is really crucial for work with `async` applications. I'd like to ask (a) what, if any, async support does this library offer? (b) Is there a roadmap for async feautures? And (c) what features are planned for this?

Cheers!

**Comment by tonybaloney** [comment]
Great question, I'm still working on the basics for this library, but one of the first production use cases is an async worker and the reason I started this project is because the standard library logging module causes such an overhead.

I'll have a think about this next and update the thread

**Comment by Goldziher** [comment]
Great. I'd gladly contribute as well when there is more clarity

**Comment by tonybaloney** [comment]
Looking at the stdlib implementation, it was added in Python 3.2. I'd probably do it differently today. It's using pickling/`copy.copy` for thread safety and a worker thread, but a single one. 

Firstly adding an async Handler and Logger specification, with a coroutine for `.info()`, `.warning()` etc. and then using an internal asyncio queue to write records and then sending those to the handlers in a worker thread, or within the coroutine. There are async stream writers for the outputs of the handler, so it would implement coroutines from top to bottom.

This library only supports Python 3.7+ anyway.

Not sure on the performance gains/losses compared to the queue, listener and worker thread approach. 

What do you think?

**Comment by Goldziher** [comment]
Sounds good. I also don't know about the performance differences, but I would assume that an async approach would scale better .

**Comment by tonybaloney** [comment]
Try 0.6.0, it comes with a queue handler and listener. I'm working on the async stuff later
