### ISSUE TITLE
`getLevelName` is missing a part of the behavior

### ISSUE THREAD

**Issue by alexprengere** [microsoft/picologging#51]
[`logging.getLevelName`](https://docs.python.org/3/library/logging.html#logging.getLevelName) works as a two way street between level and level names:

```python
>>> import logging
>>> logging.getLevelName(logging.WARNING)
'WARNING'
>>> logging.getLevelName("WARNING")
30
```
In picologging, the second way raises a TypeError:

```python
>>> logging.getLevelName("WARNING")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: level must be an integer
```

**Comment by aminalaee** [comment]
I agree that for the sake of backwards compatibility this should be modified,
but is there a specific use-case for it or just to be on par with `logging`?
It's really a weird behaviour.

**Comment by alexprengere** [comment]
I have used it in a private codebase to convert a logging level as a `str` to the corresponding `int`, so roughly:

```python
import logging
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("logging-level", default="DEBUG")
...
args = parser.parse_args()

level = logging.getLevelName(args.logging_level)
logging.basicConfig(..., level=level)
```

There are other ways to implement this (with their own problems..):
+ `level = getattr(logging, args.logging_level)`
+ `level = logging._nameToLevel[args.logging_level]`

I totally agree that this behavior of `logging.getLevelName` is out of place, and should be under its own function `logging.getLevelFromName` or so. The docs mention it too:

> Changed in version 3.4: In Python versions earlier than 3.4, this function could also be passed a text level, and would return the corresponding numeric value of the level. This undocumented behaviour was considered a mistake, and was removed in Python 3.4, but reinstated in 3.4.2 due to retain backward compatibility.

**Comment by aminalaee** [comment]
Yeah I agree, seems like it shiuld be just kept for backwards conpatibility.
