### ISSUE TITLE
Add support for `dictConfig`

### ISSUE THREAD

**Issue by MrAwesomeRocks** [microsoft/picologging#53]
[`logging.config.dictConfig`](https://docs.python.org/3/library/logging.config.html#logging.config.dictConfig) is an extremely powerful configuration tool, especially when using more complicated logging pipelines such as with [StructLog](structlog.org/). It would be very useful to have it in picologging.

The implementation is mainly in the [DictConfigurator](https://github.com/python/cpython/blob/54ea127923eee1672fd67cc96a4a0b10961f52ed/Lib/logging/config.py#L487) class, `logging.config.dictConfig` just defers to it.

---
Thank you very much!
This project looks awesome!

**Comment by tonybaloney** [comment]
+1 to this feature
